name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go env
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.1
      
      - name: Go version
        run: go --version
