name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: |
          whoami
          uname -a
          uptime
          cat /etc/*release

      - name: Setup Go env
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.1

      - name: Go version
        run: go version

  docker:
    name: docker
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Environment
        run: |
          whoami
          uname -a
          pwd
          uptime
          cat /etc/*release
          mount

      - name: Show README
        run: |
          cat README.md
