name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Who I am
        run: whoami

      - name: Where I am
        run: uname -a
