name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: |
          whoami
          uname -a
          uptime
          cat /etc/*release

      - name: Setup Go env
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17.1

      - name: Go version
        run: go version

  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show README
        run: |
          cat README.md

      - name: Show README inside a Docker Container
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/sh
          args: -c "cat README.md"

